// <auto-generated />
namespace Tienda.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AñadidoRut_Isbloqued_Usuarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AñadidoRut_Isbloqued_Usuarios));
        
        string IMigrationMetadata.Id
        {
            get { return "201711120025228_AñadidoRut_Isbloqued_Usuarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
